import { builtinModules } from "node:module";
import type { Plugin } from "vite";
import { defineConfig } from "vite";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE + ROLLDOWN
if you want to view the source, please visit the github repository of this plugin
*/
`;

function bannerPlugin(): Plugin {
	return {
		name: "banner-plugin",
		generateBundle(_options, bundle) {
			for (const chunk of Object.values(bundle)) {
				if (chunk.type === "chunk") {
					chunk.code = banner + chunk.code;
				}
			}
		},
	};
}

export default defineConfig(({ mode }) => {
	const isProd = mode === "production";

	return {
		plugins: [bannerPlugin()],
		build: {
			outDir: ".",
			emptyOutDir: false,
			lib: {
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			sourcemap: isProd ? false : "inline",
			minify: isProd,
			rollupOptions: {
				external: [
					"obsidian",
					"electron",
					"@codemirror/autocomplete",
					"@codemirror/collab",
					"@codemirror/commands",
					"@codemirror/language",
					"@codemirror/lint",
					"@codemirror/search",
					"@codemirror/state",
					"@codemirror/view",
					"@lezer/common",
					"@lezer/highlight",
					"@lezer/lr",
					...builtinModules,
				],
				output: {
					entryFileNames: "main.js",
				},
			},
		},
		test: {
			globals: true,
			environment: "node",
			include: ["src/**/*.test.ts"],
			coverage: {
				provider: "v8",
				reporter: ["text", "json", "html"],
				exclude: ["node_modules/", "src/**/*.test.ts"],
			},
			server: {
				deps: {
					external: ["obsidian"],
				},
			},
		},
	};
});
